---
kind: pipeline
type: kubernetes
name: build

trigger:
  event:
    - push


steps:

  - name: create-pypirc-file-for-codeartifact
    image: python:3.10
    depends_on:
      - clone
    environment:
      CODEARTIFACT_USERNAME:
        from_secret: CODEARTIFACT_USERNAME
      AWS_ACCOUNT_ID:
        from_secret: AWS_ACCOUNT_ID
      CODEARTIFACT_AUTH_TOKEN:
        from_secret: CODEARTIFACT_AUTH_TOKEN
      CODEARTIFACT_PYPI_REGISTRY:
        from_secret: CODEARTIFACT_PYPI_REGISTRY
    commands:
    - pip install -U pip==23.2.1
    - pip install --quiet awscli twine==4.0.2 packaging==23.1 bumpversion
    - touch .pypirc
    - echo $CODEARTIFACT_USERNAME
    - echo $CODEARTIFACT_AUTH_TOKEN
    - echo "[distutils]" > .pypirc
    - echo "index-servers =" >> .pypirc
    - echo "    codeartifact" >> .pypirc
    - echo >> .pypirc
    - echo "[codeartifact]" >> .pypirc
    - echo "repository:$CODEARTIFACT_PYPI_REGISTRY" >> .pypirc
    - echo "username:$CODEARTIFACT_USERNAME" >> .pypirc
    - echo "password:$CODEARTIFACT_AUTH_TOKEN" >> .pypirc
    - echo >> .pypirc

  - name: lint-and-type-check
    image: python:3.9-slim
    environment:
      AWS_ACCOUNT_ID:
        from_secret: AWS_ACCOUNT_ID
      CODEARTIFACT_AUTH_TOKEN:
        from_secret: CODEARTIFACT_AUTH_TOKEN
      CODEARTIFACT_USERNAME:
        from_secret: CODEARTIFACT_USERNAME
    commands:
      - pip install -U pip==21.3.1
      - pip install awscli
      - export CODEARTIFACT_AUTH_TOKEN=$CODEARTIFACT_AUTH_TOKEN
      # - ./entrypoint.sh lint
      # - ./entrypoint.sh typehinting


  - name: test-py39-latest
    image: python:3.9-slim
    environment:
      AWS_ACCOUNT_ID:
        from_secret: AWS_ACCOUNT_ID
      CODEARTIFACT_AUTH_TOKEN:
        from_secret: CODEARTIFACT_AUTH_TOKEN
      CODEARTIFACT_USERNAME:
        from_secret: CODEARTIFACT_USERNAME
    commands:
      - pip install -U pip==21.3.1
      - pip install awscli
      - export CODEARTIFACT_AUTH_TOKEN=$CODEARTIFACT_AUTH_TOKEN
      # - ./entrypoint.sh test


  - name: release-python-library-codeartifact
    image: python:3.10-slim
    environment:
      AWS_ACCESS_KEY_ID:
        from_secret: AWS_ACCESS_KEY_ID
      AWS_SECRET_ACCESS_KEY:
        from_secret: AWS_SECRET_ACCESS_KEY
      AWS_ACCOUNT_ID:
        from_secret: AWS_ACCOUNT_ID
    depends_on:
      - create-pypirc-file-for-codeartifact
    commands:
      - cat .pypirc
      - pip install -U pip==23.2.1
      - pip install --quiet awscli twine==4.0.2 packaging==23.1 bumpversion
      - bumpversion minor --allow-dirty --new-version `/bin/date +%Y.%-V`.${DRONE_BUILD_NUMBER}
      - export version=$(cat .bumpversion.cfg | awk '/current_version / {print $3}')
      - export CODEARTIFACT_AUTH_TOKEN=$CODEARTIFACT_AUTH_TOKEN
      - python setup.py sdist bdist_wheel
      - twine upload --repository codeartifact dist/globality-black-$${version}.tar.gz --config-file .pypirc
    # when:
    #   branch:
    #     - master

---
kind: pipeline
type: kubernetes
name: pr

trigger:
  event:
    - pull_request

steps:
  - name: dependency-validation-dummy
    pull: always
    image: python:3.9-slim
    commands:
      - echo "Dummy step to trigger dependency-validation"

# ARTIFACTORY SECRETS.
---
kind: secret
name: SONARQUBE_TOKEN
get:
  path: secrets/dev/drone
  name: DRONE_SONARQUBE_TOKEN

---
kind: secret
name: AWS_ACCOUNT_ID
get:
  path: secrets/dev/drone
  name: AWS_ACCOUNT_ID

---
kind: secret
name: PYPI_TOKEN
get:
  path: secrets/dev/drone
  name: PYPI_TOKEN

---
kind: secret
name: ARTIFACTORY_USERNAME
get:
  path: secrets/dev/drone
  name: DRONE_ARTIFACTORY_USERNAME

---
kind: secret
name: ARTIFACTORY_PASSWORD
get:
  path: secrets/dev/drone
  name: DRONE_ARTIFACTORY_PASSWORD

---
kind: secret
name: GITHUB_PRIVATE_KEY
get:
  path: secrets/dev/drone
  name: DRONE_GITHUB_PRIVATE_KEY

---
kind: secret
name: DRONE_API_TOKEN
get:
  path: secrets/dev/drone
  name: DRONE_API_TOKEN

# CODEARTIFACT SECRETS
---
kind: secret
name: CODEARTIFACT_USERNAME
get:
  path: secrets/dev/codeartifact
  name: CODEARTIFACT_USERNAME

---
kind: secret
name: CODEARTIFACT_AUTH_TOKEN
get:
  path: secrets/dev/codeartifact
  name: CODEARTIFACT_AUTH_TOKEN

---
kind: secret
name: CODEARTIFACT_PYPI_REGISTRY
get:
  path: secrets/dev/codeartifact
  name: CODEARTIFACT_PYPI_REGISTRY

---
kind: secret
name: CODEARTIFACT_EXTRA_INDEX_URL
get:
  path: secrets/dev/codeartifact
  name: CODEARTIFACT_EXTRA_INDEX_URL